### ISSUE TITLE
Is PyPI a version behind?

### ISSUE THREAD

**Issue by ausbin** [SupertechLabs/SupermarQ#59]
Hi folks,

Is it intentional that [PyPI has supermarq 0.0.4](https://pypi.org/project/SupermarQ/) yet this repository has [a 0.1.0 release](https://github.com/SupertechLabs/SupermarQ/releases/tag/v0.1.0)?

I ran into some problems with 0.0.4 (installed from PyPI) but 0.1.0 (installed locally) fixed them, which is why I ask

Thanks for this repo, it's very useful

**Comment by vtomole** [comment]
Thanks for the catch @ausbin . Looks like the deploy script [failed ](https://github.com/SupertechLabs/SupermarQ/actions/runs/2968243286). I've deployed `0.1.0` manually which should now be [here](https://pypi.org/project/SupermarQ/0.1.0/). I'll close this issue once the deploy script is fixed by https://github.com/SupertechLabs/SupermarQ/pull/60

**Comment by teaguetomesh** [comment]
Closing this issue since #60 was merged and pypi is up to date.
